# Generated by Django 3.1.3 on 2020-11-25 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201125_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.timezone),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='time_in',
            field=models.DateTimeField(blank=True, default=datetime.timezone),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='time_out',
            field=models.DateTimeField(blank=True, default=datetime.timezone),
        ),
    ]
