# Generated by Django 3.1.3 on 2020-11-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201125_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='time_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
